import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/ui-elements/TopBar";
import Header from "@/components/ui-elements/Header";
import Footer from "@/components/ui-elements/Footer";
import ThemeProvider from "@/components/providers/ThemeProvider";

const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-flex",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "BlueRock",
  description: "Generated by create next app",
};

export default function RootLayout({
   children,
    }: Readonly<{
    children: React.ReactNode;
    }>) {
    return (
        <html lang="en" className={robotoFlex.variable} suppressHydrationWarning>
            <body className={`${robotoFlex.className} antialiased`}>
                <ThemeProvider>
                    <TopBar />
                    <Header />
                    <main id="main-content">
                        {children}
                    </main>
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
